# Generated by Django 3.0.6 on 2020-05-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='plate_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^\\w{6}$')]),
        ),
    ]
