# Generated by Django 3.0.6 on 2020-05-15 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0003_platesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Illegal characters used', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='plate',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Illegal characters used', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plate_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Accepted plate format: AAA111', regex='^[a-zA-Z]{3}\\d{3}$')]),
        ),
    ]
